server {
  listen 80;
  server_name _;

  location = / {
    root /usr/share/nginx/html;
    try_files /index.html =404;
  }

  location /api/ {
    proxy_pass http://tempo:3200/api/;
    proxy_set_header Host $host;
  }

  location /ready {
    proxy_pass http://tempo:3200/ready;
    proxy_set_header Host $host;
  }
}
